version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3005:3005"
    volumes:
      - .:/app
    depends_on:
      - banco
    env_file:
      - .env
    networks: 
      - nest
    restart: always
  banco:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./_data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=seguranca
      # - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks: 
      - nest
networks:
    nest:
        driver: bridge