# Dockerfile.api
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Instalar dotenv para ler o arquivo .env
RUN npm install dotenv

COPY . .

# Copiar o script wait-for-it.sh
# COPY wait-for-it.sh /wait-for-it.sh
# RUN chmod +x /wait-for-it.sh

CMD ["sh", "-c", "./wait-for-it.sh banco:5432 -- npm run start"]
