version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: sh -c "./wait-for-it.sh banco:5432 -- npm run start"
    ports: 
      - "3005:3005"
    volumes:
      - .:/app
    depends_on:
      - banco
    env_file:
      - .env

  banco:
    build: 
      context: .
      dockerfile: Dockerfile.banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=seguranca
      - POSTGRES_INITDB_ARGS="--encoding=UTF8 --lc-collate='pt_BR.UTF-8' --lc-ctype='pt_BR.UTF-8'"

volumes:
  pgdata:
