# Use a imagem do PostgreSQL versão 15 como base
FROM postgres:15

# Variáveis de ambiente
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=@@123
ENV POSTGRES_DB=seguranca
ENV POSTGRES_INITDB_ARGS="--encoding=UTF8 --lc-collate='pt_BR.UTF-8' --lc-ctype='pt_BR.UTF-8'"

# Copie o script de inicialização para o diretório específico
COPY init-db.sh /docker-entrypoint-initdb.d/

# Exponha a porta PostgreSQL
EXPOSE 5432
