# Use the official Node.js image as the base (choose the appropriate version for your application)
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy the rest of the project files to the container
COPY . .

RUN npx prisma migrate dev

# Expose the port used by your Nest.js application (if needed)
EXPOSE 3005

# Command to start the Nest.js application
CMD ["npm", "run", "start"]
